// Bloom's Taxonomy verbs categorized by cognitive level (ordered from highest to lowest)
export const bloomTaxonomy = {
  Create: [
    "compose",
    "construct",
    "create",
    "design",
    "develop",
    "formulate",
    "hypothesize",
    "invent",
    "plan",
    "produce",
  ],
  Evaluate: [
    "appraise",
    "argue",
    "assess",
    "critique",
    "defend",
    "evaluate",
    "judge",
    "justify",
    "recommend",
    "support",
  ],
  Analyze: [
    "analyze",
    "categorize",
    "compare",
    "contrast",
    "differentiate",
    "examine",
    "experiment",
    "question",
    "test",
    "distinguish",
  ],
  Apply: [
    "apply",
    "calculate",
    "develop",
    "implement",
    "modify",
    "operate",
    "practice",
    "prepare",
    "solve",
    "use",
  ],
  Understand: [
    "classify",
    "compare",
    "contrast",
    "demonstrate",
    "explain",
    "illustrate",
    "interpret",
    "paraphrase",
    "summarize",
    "translate",
  ],
  Remember: [
    "define",
    "describe",
    "identify",
    "label",
    "list",
    "match",
    "name",
    "recall",
    "recognize",
    "state",
  ],
} as const;
